### ISSUE TITLE
Fascinating library, excited to try, sensors?

### ISSUE THREAD

**Issue by tablatronix** [FabioBatSilva/ArduinoFake#19]
Does anyone know of a mock sensor library of classes that can be used for simulating realistic sensor data using maths and not just rand ?

Would be a nice addition

**Comment by FabioBatSilva** [comment]
This lib relies on https://github.com/eranpeer/FakeIt for the mocks if the lib is compatible you should be able to mock it..

But it would be impractical to support all Arduino libraries as part of this project. 
So you have to rely on the upstream libs being compatible or provide you won headers for the lib you are using..
