### ISSUE TITLE
What licence?

### ISSUE THREAD

**Issue by fionn-r** [FabioBatSilva/ArduinoFake#30]
Thanks for the great work, it is very handy! 

I'm just a bit curious if there has been a licence chosen for this project? [According to Github]:(https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

But I can see that you have guidelines for contributing which suggests that you're ok with people creating derivative works. Could you clarify?

**Comment by FabioBatSilva** [comment]
Added a license file..
