### ISSUE TITLE
how to handle arduino core libraries from other platforms?

### ISSUE THREAD

**Issue by peterus** [FabioBatSilva/ArduinoFake#38]
I am working a lot on ESP32 mcu's. This arduino core's have some libraries which are used a lot (WiFi, UDP, Ethernet, etc.).

1. Do somebody know of a ESP32 Arduino Fake core/library?
2. Is it possible to integrate this kind of libraries here? but I think this will make this project not really better for other core's (like AVR etc.)

how do you handle situations like this?

**Comment by hansmbakker** [comment]
I tried copying the public part of the relevant header files to a separate folder, including their dependencies.

I gave them a different name, like `HTTPCLient_Mock.h`, `WiFiClient.h`. I removed the `#include` for the  `Client` class in `WiFiClient.h` and replaced it by `class Client;`

In my code I conditionally include the real or mocking headers:
```cpp
#ifdef UNIT_TEST
#include "HTTPClient_Mock.h"
#else
#include <HTTPClient.h>
#endif
```

It feels like a lot of tinkering to get it right though. More guidance from the maintainer would be great here.
