### ISSUE TITLE
Upgrade the `fakeit` lib?

### ISSUE THREAD

**Issue by MacDada** [FabioBatSilva/ArduinoFake#44]
https://github.com/FabioBatSilva/ArduinoFake/tree/master/src/fakeit – currently it is a hardcoded, very old version.

I actually came here to fix a few issues that the lib is throwing at me, when I build my tests with `-Wpedantic`. But I see what's going on now -> and I don't think trying to fix the old hardcoded version would be a good idea ;-)

A better one would be:
1. Upgrade `fakeit` to its latest available version.
2. Not hardcode it anymore -> maybe download it with PIO's `lib_deps`?

**Comment by FabioBatSilva** [comment]
@MacDada, This PR is updating the fakeit but.

But i haven't had the time to test out the impact of the breaking changes yet (Thanks @RobertByrnes): https://github.com/FabioBatSilva/ArduinoFake/pull/41

If you have the chance please. 
Try it out that version and let us know on #41 what breaks for you
