### ISSUE TITLE
undefined reference to `yield'

### ISSUE THREAD

**Issue by dolfandringa** [FabioBatSilva/ArduinoFake#8]
I see yield is defined in `arduino/Arduino.h` but not implemented anywhere. I am using ArduinoFake with DallasTemperature, which uses the `yield` function, which causes the following compile error: `undefined reference to `yield'`. How is yield supposed to be implemented? I don't care what it does (it won't even be called), but my efforts at implementing it  myself with am empty function didn't work.

**Comment by FabioBatSilva** [comment]
Hi..

The `yield`  is not supported by `ArduinoFake` yet..

If you want to contribute and implement the missing functionality
You can follow this instructions here on [Contribution Guidelines](https://github.com/FabioBatSilva/ArduinoFake/blob/master/CONTRIBUTING.md)

**Comment by dolfandringa** [comment]
Made a PR

**Comment by FabioBatSilva** [comment]
Closed by https://github.com/FabioBatSilva/ArduinoFake/pull/10
